name: Docker镜像制作

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Dockerfile路径'
        required: true
      image_name:
        description: 'Docker镜像名称'
        required: true
      image_version:
        description: 'Docker镜像版本'
        required: true
        default: 'latest'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build . --file ${{ github.event.inputs.dockerfile_path }} --tag ${{ github.event.inputs.image_name }}:latest
      if: github.event_name == 'workflow_dispatch'
    
    - name: Build the Docker image (default)
      run: |
        docker build . --file docker/linux_arm64/Dockerfile --tag ${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_version }}
      if: github.event_name != 'workflow_dispatch'

    - name: Save Docker image as tar file
      run: |
        docker save -o ${{ github.event.inputs.image_name }} ${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_version }}
      if: github.event_name == 'workflow_dispatch'

    - name: Upload Docker image tar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.image_name }}
        path: ${{ github.event.inputs.image_name }}
      if: github.event_name == 'workflow_dispatch'
