name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build . --file docker/linux_amd64/Dockerfile --tag my-image-name:latest

    - name: Save Docker image as tar file
      run: |
        docker save -o my-image.tar my-image-name:latest

    - name: Upload Docker image tar file
      uses: actions/upload-artifact@v4  # ✅ 使用最新稳定版本
      with:
        name: my-image.tar
        path: my-image.tar
